# Generated by Django 4.0.2 on 2022-07-08 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0003_alter_room_options_room_participents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participents',
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
